language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
before_install:
  - if [[ `node --version` =~ "v0.10" ]]; then npm install -g npm@latest; fi
  - printf "//registry.npmjs.org/:_authToken=$TOKEN" >> ~/.npmrc
